name: ASPICE Release PR Validation

on:
  pull_request:
    branches: 
      - 'releases/**'

jobs:
  self-hosted-env-check:
    name: Self-Hosted Environment Check
    runs-on: [self-hosted, ASPICE]
    steps:
      - name: Print Host Information
        run: |
          echo "Running on self-hosted ASPICE runner"
          echo "Hostname: $(hostname)"
          echo "OS details: $(uname -a)"
          echo "OS Version: $(cat /etc/os-release | grep PRETTY_NAME | cut -d= -f2 | tr -d '"')"
          echo "CPU Info: $(grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | sed 's/^[ \t]*//')"
          echo "Memory: $(free -h | grep Mem | awk '{print $2}')"
          echo "Disk space: $(df -h / | awk 'NR==2 {print $2}')"
          
  check-source-branch:
    name: Check Source Branch
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'dev/')
    steps:
      - name: Source Branch Check
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          echo "Target branch: ${{ github.base_ref }}"
          echo "This workflow only runs for PRs from dev/* branches to release/* branches"

  release-validation:
    name: Release Validation
    runs-on: ubuntu-latest
    needs: check-source-branch
    container:
      image: golang:1.21-bullseye
      options: --user root
    steps:
      - uses: actions/checkout@v3
          
      - name: Test with coverage
        run: make test-coverage
        
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: release-coverage
          path: |
            ./coverage.txt
            
      - name: Verify Test Coverage
        run: |
          # Extract coverage percentage
          COVERAGE=$(go tool cover -func=coverage.txt | grep total | awk '{print $3}' | tr -d '%')
          echo "Test coverage: $COVERAGE%"
          
          # Fail if coverage is below threshold (e.g., 80%)
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "Error: Test coverage is below the required threshold of 80%"
            exit 1
          fi